server:
  port: 80

spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848    # nacos 注册中心地址
    gateway:
      discovery:
        locator:
          enabled: true     #开启从注册中心动态创建路由的功能，利用微服务名进行路由    #开启默认serverID小写
          lower-case-service-id: true       #开启默认serverID小写
      routes:
        - id: admin-server_router   #admin-server 的网关,也算是唯一标识
          uri: lb://app1            #lb负载均衡       uri代表转发到哪一个目的地
          predicates:      # 断言预言，当路径是 /admin/ 开头的，就转发到 uri对应的服务
            - Path=/admin/**
#        id: test-server_router
#          uri: http://www.baidu.com
#          predicates:      # 断言预言，当路径是 /admin/ 开头的，就转发到 uri对应的服务
#            - Path=/test